### ISSUE TITLE
An official release tag?

### ISSUE THREAD

**Issue by Commander-Zal** [laanwj/sundog#1]
Hi Laanwj,

I stumbled across your lovely port of Sundog today after doing some research on the game, and would absolutely love for it to be included in my favored Linux distro, [Solus](https://solus-project.com/), so that others may enjoy this unique title (maybe even becoming excited enough to consider expanding upon your efforts?).

However, to be [eligible for inclusion into the Solus repo's](https://solus-project.com/articles/packaging/package-inclusion-policy/en/), a program generally must have an official 'stable' release of some sort.

Would it be possible to tag the latest build here on github as a 1.0 release? I understand there's still a few non-critical things missing from the game, but seeing as it's still fully working & playable, it _should_ be eligible for inclusion were it tagged as such.

Thank you for your time and consideration, and for porting this hidden gem.
Cheers! :)

**Comment by laanwj** [comment]
I have been putting this off because building binaries for various platforms is a time-sink I can't use right now.
However I didn't think of packagers and downstream.
I've just pushed a tag for the initial version: https://github.com/laanwj/sundog/tree/v0.1.0
Cheers!

**Comment by Commander-Zal** [comment]
Thanks a ton, man! I'll get to submitting a request to add this to the repos right away. [Much appreciated.](https://media.giphy.com/media/26gJA2YrG9FS5PyrS/giphy.gif) ^_^
