### ISSUE TITLE
I must be doing something wrong.

### ISSUE THREAD

**Issue by wdcallahan** [laanwj/sundog#2]
I pulled the repo. I installed the libraries. I typed make. I have no idea what went wrong. Am I still missing a library? 
I have attached my output.
[problem.txt](https://github.com/laanwj/sundog/files/3030472/problem.txt)

**Comment by laanwj** [comment]
Hey! That's strange, which distribution and gcc version is this ?

It looks like it is suggesting to add `#include <stdio.h>` at the top of `util/debugger.c`, can you try this?

**Comment by wdcallahan** [comment]
gcc (GCC) 8.3.1 20190223 (Red Hat 8.3.1-2)

Fedora release 29 (Twenty Nine)

I added the line and then everything worked. I had the same problem on sundog-0.1.0 and  sundog-master.

**Comment by laanwj** [comment]
Pushed that fix to master as f190e40a765b4a82c3c34b07e45f0a044770eaae

As for the `.st` image, it's kind of finicky with which disk images work. It needs to be directly extracted from the original disk, not a compressed multi-game disk (which were way more common in the day).

This one should work: https://download.visucore.com/sundog/new_disk.st
