### ISSUE TITLE
I want to extract all the game's Atari ST art assets.

### ISSUE THREAD

**Issue by MechMel** [laanwj/sundog#26]
I want attempt to recreate parts of the original Sundog game for a fun. I was trying to extract the original art assets via screen shots and then recolor them, but I realized that it might be easier see if there was a way to just extract the assets from the original game. Is an easy way to do this?

**Comment by laanwj** [comment]
Yes, that's fairly easy. There's a few different assets and scripts to export them:

- `src/rip_images.c` exports the static images (map tiles etc)
- `tools/extract_gfx.py` extracts the font
- `tools/dump_sprites.py` dumps a few sprites

There's also the item icon,s I don't exactly remember how to export those right now, I'll post when I can remember or just upload them :smile:

**Comment by laanwj** [comment]
The item icons:
![sundog_items](https://github.com/laanwj/sundog/assets/126646/03110ada-57c1-4565-acac-e962cfc23207)

**Comment by MechMel** [comment]
Sweet! Thanks a bunch!

**Comment by laanwj** [comment]
Let me know how it goes!

**Comment by MechMel** [comment]
I could only work on it a bit here and there, and it took me a bit to figure out the extractors, but it worked excellently, and I got everything. Thanks!

**Comment by laanwj** [comment]
Woohoo!
