### ISSUE TITLE
Teleporting and slot machine issue 

### ISSUE THREAD

**Issue by murasame78** [laanwj/sundog#33]
Hi! Great work you've been doing.

I successfully managed to compile it on my Raspberry pi 5.

2 issues I've noticed while playing the game so far : 

- When using the Public Teleport, upon clicking the "Deposit money" button, you instantly get teleported without a chance to choose any specific spot.
- When using the slots machine, the result pops up instantly upon paying.

Anyone facing the same issues ?

**Comment by laanwj** [comment]
Both issues should be fixed on the main branch.
